#端口
server:
  port: 8080

debug: true

mybatis-plus:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.example.picture.pojo; com.example.picture.dto;
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true

spring:
  profiles:
    include: email, sa_token, mydata, redis, datasource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB

